/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CameraWorld {
  constructor()
  ingest(timestampMs: number, detections: Array<Detection>, cameraMotion?: CameraMotion | undefined | null): WorldIngestResult
  setLines(lines: Array<DetectionLine>, aspectRatio: number): void
  /** PTZ moved: identities and anchors are position-based and start over. */
  notifyCameraMove(): void
  setZones(zones: Array<DetectionZone>): void
  setMinConfidence(minConfidence: number): void
  /** Indices of detections that pass zones and min confidence. */
  filterIndices(detections: Array<Detection>): Array<number>
}

export interface BoundingBox {
  x: number
  y: number
  width: number
  height: number
}

export declare function boxIou(a: BoundingBox, b: BoundingBox): number

/**
 * Camera ego-motion for one frame step in normalized coords; when supplied
 * to `update()`, Kalman predictions are transformed to survive pans.
 */
export interface CameraMotion {
  x: number
  y: number
}

export interface Detection {
  x: number
  y: number
  width: number
  height: number
  confidence: number
  label: string
}

/**
 * `points` are the two handle endpoints in `[0, 100]` UI coordinates;
 * empty `labels` means "any label".
 */
export interface DetectionLine {
  name: string
  direction: LineDirection
  labels: Array<string>
  points: Array<Array<number>>
}

/** `points` are polygon vertices in `[0, 100]` UI coordinates; auto-closed. */
export interface DetectionZone {
  labels: Array<string>
  filter: ZoneFilterMode
  /** Mapped to `type` on the JS side of the SDK. */
  matchType: ZoneMatchType
  isPrivacyMask: boolean
  points: Array<Array<number>>
}

export interface LineCrossingEvent {
  lineName: string
  direction: LineDirection
  trackId: number
  label: string
  confidence: number
  timestampMs: number
  prevX: number
  prevY: number
  currX: number
  currY: number
}

export declare const enum LineDirection {
  Both = 'both',
  AToB = 'a-to-b',
  BToA = 'b-to-a'
}

export declare function merge(detections: Array<Detection>, iouThreshold: number, closeThreshold: number): Array<Detection>

export declare function nms(detections: Array<Detection>, iouThreshold: number, maxDetections?: number | undefined | null): Array<Detection>

export declare function nmsIndices(detections: Array<Detection>, iouThreshold: number): Array<number>

export interface WorldEvent {
  /**
   * One of: objectEntered, objectLost, objectRecovered, objectSettled,
   * objectWoke, objectDeparted, bestShotUpdated.
   */
  eventType: string
  object: WorldObject
}

export interface WorldIngestResult {
  tracked: Array<WorldObject>
  /** World ids that got a new identity this tick (re-associations excluded). */
  created: Array<number>
  /** World ids that departed this tick. */
  removed: Array<number>
  events: Array<WorldEvent>
  crossings: Array<LineCrossingEvent>
}

export interface WorldObject {
  trackId: number
  label: string
  x: number
  y: number
  width: number
  height: number
  confidence: number
  speed: number
  velocityX: number
  velocityY: number
  /** One of: tentative, active, stationary, lost, departed. */
  state: string
}

export declare const enum ZoneFilterMode {
  Include = 'include',
  Exclude = 'exclude'
}

export declare const enum ZoneMatchType {
  /** Any overlap with the polygon counts. */
  Intersect = 'intersect',
  /** All four corners must be inside the polygon. */
  Contain = 'contain'
}
