/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CameraWorld {
  constructor()
  ingest(timestampMs: number, detections: Array<Detection>, cameraMotion?: CameraMotion | undefined | null): WorldIngestResult
  setLines(lines: Array<DetectionLine>, aspectRatio: number): void
  notifyCameraMove(): void
  setZones(zones: Array<DetectionZone>): void
  setMinConfidence(minConfidence: number): void
  filterIndices(detections: Array<Detection>): Array<number>
}

export interface BoundingBox {
  x: number
  y: number
  width: number
  height: number
}

export declare function boxIou(a: BoundingBox, b: BoundingBox): number

export interface CameraMotion {
  x: number
  y: number
}

export interface Detection {
  x: number
  y: number
  width: number
  height: number
  confidence: number
  label: string
}

export interface DetectionLine {
  name: string
  direction: LineDirection
  labels: Array<string>
  points: Array<Array<number>>
}

export interface DetectionZone {
  labels: Array<string>
  filter: ZoneFilterMode
  matchType: ZoneMatchType
  isPrivacyMask: boolean
  points: Array<Array<number>>
}

export interface LineCrossingEvent {
  lineName: string
  direction: LineDirection
  trackId: number
  label: string
  confidence: number
  timestampMs: number
  prevX: number
  prevY: number
  currX: number
  currY: number
}

export declare const enum LineDirection {
  Both = 'both',
  AToB = 'a-to-b',
  BToA = 'b-to-a'
}

export declare function merge(detections: Array<Detection>, iouThreshold: number, closeThreshold: number): Array<Detection>

export declare function nms(detections: Array<Detection>, iouThreshold: number, maxDetections?: number | undefined | null): Array<Detection>

export declare function nmsIndices(detections: Array<Detection>, iouThreshold: number): Array<number>

export interface WorldEvent {
  /**
   * One of: objectEntered, objectLost, objectRecovered, objectSettled,
   * objectWoke, objectDeparted, bestShotUpdated.
   */
  eventType: string
  object: WorldObject
}

export interface WorldIngestResult {
  tracked: Array<WorldObject>
  created: Array<number>
  removed: Array<number>
  events: Array<WorldEvent>
  crossings: Array<LineCrossingEvent>
}

export interface WorldObject {
  trackId: number
  label: string
  x: number
  y: number
  width: number
  height: number
  confidence: number
  speed: number
  velocityX: number
  velocityY: number
  /** One of: tentative, active, stationary, lost, departed. */
  state: string
}

export declare const enum ZoneFilterMode {
  Include = 'include',
  Exclude = 'exclude'
}

export declare const enum ZoneMatchType {
  Intersect = 'intersect',
  Contain = 'contain'
}
